require "user.impatient"
require "user.options"
require "user.keymaps"
require "user.commands"
require "user.plugins"
require "user.autocommands"
require "user.cmp"
require "user.telescope"
require "user.gitsigns"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.lualine"
require "user.toggleterm"
require "user.illuminate"
require "user.indentline"
require "user.lsp"
require "user.dap"

require "user.which-key"
require "user.nvim-surround"
require "user.session-manager"
require "user.dressing"
-- require "user.onedark"
require "user.vscode"
require "user.colorscheme"
